# Generated by Django 5.2.5 on 2026-08-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_usuario_foto_alter_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='recibida',
            field=models.BooleanField(default=False),
        ),
    ]
